from typing import Literal

from pydantic import BaseModel, Field


class ScheduleSqlPlan(BaseModel):
    """Structured SQL plan generated by the CrewAI task."""

    action: Literal["add", "delete", "query", "delete_by_id"] = Field(
        ...,
        description="add for insert, delete for delete by title/time, query for selecting, delete_by_id for deleting by row id.",
    )
    title: str = Field(default="", max_length=255)
    schedule_time: str = Field(
        default="",
        description="Beijing time in the format YYYY-MM-DD HH:MM:SS when applicable.",
    )
    normalized_request: str = Field(
        ...,
        description="A precise normalized Chinese sentence describing the resolved schedule action.",
    )
    sql: str = Field(
        ...,
        description="The final SQL statement. It must target only the gd2 table.",
    )
    params: list[str] = Field(
        ...,
        description="Ordered SQL parameters matching the placeholders in sql.",
    )
    summary: str = Field(
        ...,
        description="A short Chinese execution summary for the user.",
    )

